spring:
  application:
    name: consumer-9091
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 9091

## 配置这个之后，远程被调用服务发生错误，那么将会走fallback的处理
feign:
  sentinel:
    enabled: true