spring:
  application:
    name: dubbo-consumer-9092
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

dubbo:
  cloud:
    subscribed-services: dubbo-provider


server:
  port: 9092